#You will be required to create a service account in the namespace first.
#Use kubectl create serviceaccount <name> -n <namespace>
#After the SA is created verify it using kubectl get serviceaccounts -n <namespace>
#Kubernetes will generate a unique token for each SA and it is stored in a secret.
#Run kubectl get secrets -n <namespace> and you shall see the new secret created for your custom SA.
#You can now mount this secret to the Pod, secrets are mounted when the Pods are created.
#In the Pod specs use serviceAccountName: <name of service account> and automountServiceAccountToken: true to
#automatically mount the corresponding secret in the pod volume. Otherwise you can just mount the secret in an explicit
#manner like any other volume on the pod and access in the containers.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-sa-demo
  labels:
    name: nginx-sa-demo
    type: demo

spec:
  containers:
    - name: nginx-sa-demo
      image: nginx:latest
  serviceAccountName: sa-volume
  automountServiceAccountToken: true