#run create-configmap-for-pod-volumes.yaml in the namespace first.
apiVersion: v1
kind: Pod
metadata:
  name: busybox-test-pod
spec:
  containers:
    - name: busybox-test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "ls /etc/config/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never